### ISSUE TITLE
[C++][Parquet] Parquet modular encryption

### ISSUE THREAD

**Issue by rok** [rok/test-parquet-cpp#579]
CPP version of a mechanism for modular encryption and decryption of Parquet files. Allows to keep the data fully encrypted in the storage, while enabling a client to extract a required subset (footer, column(s), pages) and to authenticate / decrypt the extracted data.

**Reporter**: [Gidon Gershinsky](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=gershinsky) / @ggershinsky
#### Subtasks:
- [X] [[C++] Crypto package in parquet-cpp](https://issues.apache.org/jira/browse/PARQUET-1301)
- [X] [[C++] Update cpp crypto package to match signed-off specification](https://issues.apache.org/jira/browse/PARQUET-1517)
- [X] [[C++] Add encrypted parquet files to apache parquet-testing repository](https://issues.apache.org/jira/browse/PARQUET-1621)
#### Related issues:
- [CLONE - [C++] Parquet modular encryption](https://issues.apache.org/jira/browse/PARQUET-1906) (is cloned by)
- [Parquet modular encryption](https://issues.apache.org/jira/browse/PARQUET-1178) (is depended upon by)
#### Original Issue Attachments:
- [column_reader.cc](https://issues.apache.org/jira/secure/attachment/12923429/column_reader.cc)
- [column_writer.cc](https://issues.apache.org/jira/secure/attachment/12923430/column_writer.cc)
- [file_reader.cc](https://issues.apache.org/jira/secure/attachment/12923431/file_reader.cc)
- [file_writer.cc](https://issues.apache.org/jira/secure/attachment/12923432/file_writer.cc)
- [thrift.h](https://issues.apache.org/jira/secure/attachment/12929330/thrift.h)
#### PRs and other links:
- [GitHub Pull Request #2555](https://github.com/apache/arrow/pull/2555)
- [GitHub Pull Request #4826](https://github.com/apache/arrow/pull/4826)
- [GitHub Pull Request #475](https://github.com/apache/parquet-cpp/pull/475)
- [Design](https://docs.google.com/document/d/1T89G7xR0zHFV1f2pjTO28jtfVm8qoNVGEJQ70Rsk-bY/edit?usp=sharing)

<sub>**Note**: *This issue was originally created as [PARQUET-1300](https://issues.apache.org/jira/browse/PARQUET-1300). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by rok** [comment]
[Tham](https://issues.apache.org/jira/browse/PARQUET-1300?#comment-16523387) / @thamht4190:
Thanks @ggershinsky. Looking forward to your PR with second cipher.

@majetideepak I'm curious and would like to know how you plan to change in parquet-cpp API to pass encryption key, encryption type, etc. Can you please share?

**Comment by rok** [comment]
[Tham](https://issues.apache.org/jira/browse/PARQUET-1300?#comment-16524653) / @thamht4190:
@ggershinsky Thanks for your updates. I will modify my code due to your changes and create a PR soon.
